name = "code-assist-proxy"
main = "dist/index.js"
compatibility_date = "2024-05-29"

# KV namespace binding - ID will be updated during deployment
kv_namespaces = [
  { binding = "GEMINI_CREDS_KV", id = "06ffd2dbaa3e41a093db166be089ac6f" },
]

[vars]
# Environment variables configurable during deployment
# Performance optimization flags with defaults
ENABLE_CONNECTION_POOLING = "true"
TOKEN_REFRESH_BUFFER_MINUTES = "5"
MAX_CONCURRENT_REQUESTS = "100"
CACHE_PROJECT_ID_TTL_HOURS = "1"
CIRCUIT_BREAKER_THRESHOLD = "5"
CIRCUIT_BREAKER_TIMEOUT_MS = "30000"

# Deployment configuration
[build]
command = "npm run build"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
